# Generated by Django 6.0.1 on 2026-01-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='store_id',
            new_name='store',
        ),
    ]
